name: "Daily Integration"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: vector-im/riot-web

      - name: "Install Node toolchain"
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: "Build Element package"
        run: |
          ./scripts/fetch-develop.deps.sh --depth 1
          yarn
          ./scripts/ci_package.sh

      - name: "Upload Element package"
        uses: actions/upload-artifact@v2
        with:
          name: element
          path: dist/riot-*.tar.gz

  package:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: "Unpack Element package"
        uses: actions/download-artifact@v2
        with:
          name: element

      - name: "Prepare Element for deployment"
        shell: bash
        run: |
          tar -zxvf riot-*.tar.gz -C /tmp
          xargs -n1 cp -pr /tmp/riot-* <<< "innereq thecore"
          mv innereq.jpg innereq/background.jpg
          mv innereq.json innereq/config.json
          mv thecore.png thecore/background.png
          mv thecore.json thecore/config.json

      - name: "Upload Element package for Inner Equestria"
        uses: actions/upload-artifact@v2
        with:
          name: element-innereq
          path: innereq

      - name: "Upload Element package for The Core"
        uses: actions/upload-artifact@v2
        with:
          name: element-thecore
          path: thecore

  deploy:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: "Unpack Element package for Inner Equestria"
        uses: actions/download-artifact@v2
        with:
          name: element-innereq

      - name: "Unpack Element package for The Core"
        uses: actions/download-artifact@v2
        with:
          name: element-thecore

      - name: "Debug"
        shell: bash
        run: |
          ls innereq thecore